services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: always
