name: Deploy Fullstack App to EC2 with Docker

on:
  workflow_dispatch:   # allows manual trigger from GitHub UI
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ DockerHub login
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build and push Docker images
      - name: Build and push Docker images
        run: |
          # Backend Docker build
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend:latest -f ./backend/Dockerfile ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend:latest

          # Frontend Docker build
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest

      # 4️⃣ Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/influitivezone
            git pull origin master
            docker-compose pull
            docker-compose up -d --build
