name: Deploy Fullstack App to EC2 with Docker

on:
 workflow_dispatch:   # 👈 allows manual trigger from GitHub UI
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend:latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/influitivezone
            git pull origin master
            docker-compose pull
            docker-compose up -d --build

